# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-oidc-provider
  version: "0.9.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_oidc_provider-${{ version }}.tar.gz
  sha256: 34b902577274feee71bd15bbb1b5622b4114a4f0b1efbbccb8f7a5dd4091a92a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - pyjwkest >=2.8.0
    - cryptography >=3.4.0

tests:
  - python:
      imports:
        - oidc_provider
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: OpenID Connect Provider implementation for Django.
  homepage: https://github.com/juanifioren/django-oidc-provider
  description: |
    OpenID Connect Provider implementation for Django.
  repository: https://github.com/juanifioren/django-oidc-provider
  documentation: https://django-oidc-provider.readthedocs.org
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - rxm7706
